build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  initial:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.14.0-0
        upper: 4.15.0-0
  intermediate:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.15"
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: loaded-upgrade-eus-414to416-24nodes
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale-qe
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:initial
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      CHURN: "false"
      COMPUTE_NODE_REPLICAS: "24"
      GC: "false"
      ITERATION_MULTIPLIER_ENV: "9"
      ZONES_COUNT: "3"
    test:
    - as: set-upgrade-releases
      commands: echo "${RELEASE_IMAGE_INTERMEDIATE},${RELEASE_IMAGE_TARGET}" > ${SHARED_DIR}/upgrade-edge
      dependencies:
      - env: RELEASE_IMAGE_INTERMEDIATE
        name: release:intermediate
      - env: RELEASE_IMAGE_TARGET
        name: release:latest
      from: cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - chain: openshift-qe-cluster-density-v2
    - chain: openshift-upgrade-qe-test-cpou
    workflow: openshift-qe-installer-aws-ovn-ipsec
  timeout: 8h0m0s
- always_run: false
  as: loaded-upgrade-eus-414to416-120nodes
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:initial
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      BASE_DOMAIN: perfscale.devcluster.openshift.com
      CHURN: "false"
      COMPUTE_NODE_REPLICAS: "120"
      COMPUTE_NODE_TYPE: m5.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m5.8xlarge
      ENABLE_FORCE: "true"
      EUS_CHANNEL: stable
      EUS_UPGRADE: "true"
      GC: "false"
      ITERATION_MULTIPLIER_ENV: "9"
      MAX_UNAVAILABLE: "15"
      PROFILE_TYPE: reporting
      ZONES_COUNT: "3"
    post:
    - ref: openshift-qe-kube-burner-index
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre-stableinitial
    - chain: workers-scale
    - chain: openshift-qe-cluster-density-v2
    workflow: openshift-qe-upgrade
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: aws-4.16-nightly-x86-eus-loaded-upgrade-from-4.14
